import time
import os


def printingskull(columns):
    for x in range(7):
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMM          MMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMM              MMMMMMMMMM".center(columns))
        print("MMMMMMMMM                MMMMMMMMM".center(columns))
        print("MMMMMMMM                  MMMMMMMM".center(columns))
        print("MMMMMMM                   MMMMMMMM".center(columns))
        print("MMMMMMM                    MMMMMMM".center(columns))
        print("MMMMMMM                    MMMMMMM".center(columns))
        print("MMMMMMM    MMMM    MMMM    MMMMMMM".center(columns))
        print("MMMMMMM   MMMMMM   MMMMM   MMMMMMM".center(columns))
        print("MMMMMMM   MMMMMM   MMMMM   MMMMMMM".center(columns))
        print("MMMMMMMM   MMMMM M MMMMM  MMMMMMMM".center(columns))
        print("MMVKMMMM        MMM        MMMMMMM".center(columns))
        print("MMMMMMMM       MMMMM      MMMMMMMM".center(columns))
        print("MMMMMMMMMMMM   MMMMM  MMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMM MMM       MM  MMMMMMMMM".center(columns))
        print("MMMMMMMMMM  M M M M M M MMMMMMMMMM".center(columns))
        print("MMMM  MMMMM MMMMMMMMMMM MMMMM   MM".center(columns))
        print("MMM    MMMM M MMMMMMM M MMMM    MM".center(columns))
        print("MMM    MMMM   M M M M  MMMMM   MMM".center(columns))
        print("MMMM    MMMM           MMM      MM".center(columns))
        print("MMM       MMMM       MMMM       MM".center(columns))
        print("MMM         MMMMMMMMMM      M  MMM".center(columns))
        print("MMMM  MMM      MMMMM      MMMMMMMM".center(columns))
        print("MMMMMMMMMMM  MM         MMMMMMM  M".center(columns))
        print("MMM  MMMMMMM         MMMMMMMMM   M".center(columns))
        print("MM    MMM        MMMM            M".center(columns))
        print("MM            MMMM              MM".center(columns))
        print("MMM        MMMMMMMMMMMMMMM       M".center(columns))
        print("MM      MMMMMMMMMMMMMMMMMMMMM    M".center(columns))
        print("MMM   MMMMMMMMMMMMMMMMMMMMMMMM   M".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        time.sleep(0.3)
        os.system("clear")
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMM          MMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMM              MMMMMMMMMM".center(columns))
        print("MMMMMMMMM                MMMMMMMMM".center(columns))
        print("MMMMMMMM                  MMMMMMMM".center(columns))
        print("MMMMMMM                   MMMMMMMM".center(columns))
        print("MMMMMMM                    MMMMMMM".center(columns))
        print("MMMMMMM                    MMMMMMM".center(columns))
        print("MMMMMMM    MMMM    MMMM    MMMMMMM".center(columns))
        print("MMMMMMM   MMMMMM   MMMMM   MMMMMMM".center(columns))
        print("MMMMMMM    MMMM    MMMM    MMMMMMM".center(columns))
        print("MMMMMMMM         M        MMMMMMMM".center(columns))
        print("MMVKMMMM        MMM        MMMMMMM".center(columns))
        print("MMMMMMMM       MMMMM      MMMMMMMM".center(columns))
        print("MMMMMMMMMMMM   MMMMM  MMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMM  MM       MM  MMMMMMMMM".center(columns))
        print("MMMMMMMMMM    M M M M   MMMMMMMMMM".center(columns))
        print("MMMM  MMMMM  MMMMMMMMM  MMMMM   MM".center(columns))
        print("MMM    MMMM    MMMMM    MMMM    MM".center(columns))
        print("MMM    MMMM            MMMMM   MMM".center(columns))
        print("MMMM    MMMMMM       MMMMM      MM".center(columns))
        print("MMM       MMMMMMMMMMMMMMM       MM".center(columns))
        print("MMM         MMMMMMMMMM      M  MMM".center(columns))
        print("MMMM  MMM      MMMMM      MMMMMMMM".center(columns))
        print("MMMMMMMMMMM  MM         MMMMMMM  M".center(columns))
        print("MMM  MMMMMMM         MMMMMMMMM   M".center(columns))
        print("MM    MMM        MMMM            M".center(columns))
        print("MM            MMMM              MM".center(columns))
        print("MMM        MMMMMMMMMMMMMMM       M".center(columns))
        print("MM      MMMMMMMMMMMMMMMMMMMMM    M".center(columns))
        print("MMM   MMMMMMMMMMMMMMMMMMMMMMMM   M".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        time.sleep(0.3)
        os.system("clear")
    os.system("clear")


def printinghangman(columns):
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MM                     MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMM               MMMMMMM".center(columns))
    print("MM   MMMMMMMM               MMMMMMM".center(columns))
    print("MM   MMMMMMMM               MMMMMMM".center(columns))
    print("MM   MMMMMMMM               MMMMMMM".center(columns))
    
    time.sleep(0.5)
    os.system("clear")

    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MM                     MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMM               MMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM     MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM       MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMM          MMMMMMMMM".center(columns))
    
    time.sleep(0.2)
    os.system("clear")

    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MM                     MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMM               MMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM   MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM      MMMMMMMMMM".center(columns))
    
    time.sleep(0.2)
    os.system("clear")        

    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MM                     MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM MMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM   MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM      MMMMMMMMMM".center(columns))

    time.sleep(0.2)
    os.system("clear")      
    for x in range(3):
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM     MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM     MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM   MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")  

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM     MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM     MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM     MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM M  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMM          MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM       MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM      MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM      MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM       MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM    MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMM           MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM       M  MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM      MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM      MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM      MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMM       MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM    MMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM  MMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")       

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM       M  MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM      MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM       MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM    MMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM  MMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM       MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM     MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM     MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM   MMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM          MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM          MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM          MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM         MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM       MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM      MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM   MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM          MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM          MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM          MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMM          MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMM       MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM      MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")

        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM                     MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM        MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM          MMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM          MMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM          MMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMM          MMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM        MMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMM        MMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM      MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM     MMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMM      MMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
        print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))

        time.sleep(0.3)
        os.system("clear")
    
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MM                     MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM MMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM    MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMM  MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM        MMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM     MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM     MMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMM     MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMM      MMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMM   MMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
    print("MM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMM".center(columns))
                        
                
    time.sleep(0.8)

    os.system("clear")


# printinghangman()